<?php

/**
 * @file
 * Contains modal_menu_buttons.module.
 */

use Drupal\Core\Ajax\AjaxResponse;
use Drupal\Core\Ajax\InvokeCommand;
use Drupal\Core\Ajax\OpenModalDialogCommand;
use Drupal\Core\Ajax\ReplaceCommand;
use Drupal\Core\Ajax\HtmlCommand;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\webform\Ajax\WebformScrollTopCommand;

/**
 * Implements hook_help().
 */
function modal_menu_buttons_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the modal_menu_buttons module.
    case 'help.page.modal_menu_buttons':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module for creating menu links that show up as modals') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */

function modal_menu_buttons_form_node_person_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['#attached']['library'][] = 'core/drupal.dialog.ajax';
  $form['#attached']['library'][] = 'core/drupal.ajax';
  $form['#attached']['library'][] = 'modal_menu_buttons/mover';

  $form['#prefix'] = '<div id="ajax-node-person-form">';
  $form['#suffix'] = '</div>';

  $form['status_messages'] = [
    '#type' => 'status_messages',
  ];

  $form['actions']['submit'] = [
    '#type' => 'submit',
    '#value' => t('Create Person'),
    '#attributes' => [
      'class' => [
        'use-ajax-submit',
        'btn',
        'btn-success',
      ],
    ],
    '#ajax' => [
      'callback' => 'modal_menu_buttons_node_form_submit',
      'wrapper' => 'ajax-node-person-form',
    ],
  ];
}


function modal_menu_buttons_form_node_band_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['#attached']['library'][] = 'core/drupal.dialog.ajax';
  $form['#attached']['library'][] = 'core/drupal.ajax';
  $form['#attached']['library'][] = 'modal_menu_buttons/mover';


  $form['#prefix'] = '<div id="ajax-node-band-form">';
  $form['#suffix'] = '</div>';

  $form['status_messages'] = [
    '#type' => 'status_messages',
  ];

  $form['actions']['submit'] = [
    '#type' => 'submit',
    '#value' => t('Create Band'),
    '#attributes' => [
      'class' => [
        'use-ajax-submit',
        'btn',
        'btn-success',
      ],
    ],
    '#ajax' => [
      'callback' => 'modal_menu_buttons_node_form_submit',
      'wrapper' => 'ajax-node-band-form',
    ],
  ];
}

function modal_menu_buttons_node_form_submit($form, FormStateInterface $form_state) {
  $form['#cache'] = ['max-age' => 0];
  $input =  $form_state->getUserInput();
  $response = new AjaxResponse();
  $form_state->getBuildInfo();
  // If there are any form errors, re-display the form.
  if ($form_state->hasAnyErrors()) {
    $errors = $form_state->getErrors();
    //$form_state['rebuild'] = TRUE;
    $selector = $form['actions']['submit']['#ajax']['wrapper'];
    $method ='scrollTo';
    $arguments = [$selector];
    $response->addCommand(new ReplaceCommand($selector, $form));
    return $response;
  }
  else {
    $response->addCommand(new OpenModalDialogCommand("Success!", 'Content type has been created.', ['width' => 800]));
  }
  $node_form=$form_state->getBuildInfo()['callback_object'];
  $node_form->getEntity();
  $node = $node_form->getEntity();
  $node->isNew();
  $node->save();
  $x=$form_state->getErrors();
  return $response;
};
